### ISSUE TITLE
size of output

### ISSUE THREAD

**Issue by Palashio** [kilgore92/PyTorch-UNet#3]
so when i do model(images) the number of channels for the output is equal to 2 when the input channel number is equal to 1 any idea why / how i can compute loss between the two? so if i do outputs.size() I get (1, 2, 128, 128) when my input was (1, 1, 128, 128). Is it correct? If so, how do I compute the DiceLoss between them?

**Comment by Palashio** [comment]
i figure i have to just take one of the channels and compare? but how?

**Comment by Palashio** [comment]
this is the solution i came up with let me know if it's wrong:

```python

output = output[0][0]
image = torch.reshape(image, shape=(1, 64, 64, 64))
image = torch.reshape(image, shape=(1, 1, 64, 64, 64))

```

output is the (1, 2, 128, 128, 128) image and the final output is (1, 1, 128, 128, 128).

**Comment by ishaanb92** [comment]
Hi Palash,

The Dice Loss is computed between labels. Your output dim 1 is 2 since you have one mask for the background and one for the foreground (i.e. they are inverses of each other: bg = 1 - fg). I suggest either of following 2 ways:

**Calculate dice loss over all class-labels:**
You would need to calculate the inverse of your foreground true label (i.e 1-true_mask) to get a background label mask. And then concatenated these 2 matrices along the axis=1 to get matrix of shape (1, 2, 128, 128). 

**Calculate dice loss only over foreground**
Just take the foreground part from the model prediction : output[ 0, 0, : , : , : ] and compute dice loss between this and your label. 

Cheers,
Ishaan

**Comment by ishaanb92** [comment]
Oops, I meant output[0, 1, : , : , :] to get the foreground prediction.
